### ISSUE TITLE
debounce for interrupt sensors not working

### ISSUE THREAD

**Issue by MHofer** [mysensors/NodeManager#465] opened 2019-01-24 18:20 UTC
setting a higher debounce time has no effect, even if the "setInterruptDebounce" is set to 10000ms, every activity is immediately registered and processed
in the code there is only one assignment for "_last_interrupt_millis" at line 47 of the node.cpp file, in my opinion this variable must also be updated when processing an interrupt otherwise the query at line 525 "(millis () - _last_interrupt_millis <_interrupt_debounce) "always false and the interrupt is processed

did I miss something?

i use version 1.8 and the door sensor

**Comment by user2684** [comment] 2019-01-27 15:38
I think you are right, looks like something got missing in the logic while migrating this capability from v1.7 to v1.8. I'll try to reproduce it and come back in case of doubts, meanwhile I'm tagging this as a bug

**Comment by user2684** [comment] 2020-05-10 10:26
Fixed by #517

**Closed as completed by user2684** 2020-05-10 10:26 UTC
Labels: bug
